import type { Brand } from "@/types/brand";

export const brands: Brand[] = [
  {
    id: "inkout",
    name: "inkOUT",
    slug: "inkout",
    descriptor: "TEPR non-laser removal. Specialist brand across 5 markets.",
    method: "Non-Laser",
    footprint: "National chain",
    locationCount: 5,
    markets: ["Austin, TX", "Chicago, IL", "Houston, TX", "Tampa, FL", "Draper, UT"],
    totalReviews: 194,
    avgRating: 4.4,
    tags: ["TEPR", "Non-Laser", "Top Rated"],
    featured: true,
  },
  {
    id: "removery",
    name: "Removery",
    slug: "removery",
    descriptor: "Largest dedicated laser removal chain in the US. PicoWay-based.",
    method: "Laser",
    footprint: "National chain",
    locationCount: 3,
    markets: ["Austin, TX", "Chicago, IL"],
    totalReviews: 81,
    avgRating: 3.9,
    tags: ["National Chain", "Laser", "PicoWay"],
    featured: true,
  },
  {
    id: "tatt2away",
    name: "Tatt2Away",
    slug: "tatt2away",
    descriptor: "TEPR non-laser removal with a franchise network across 3 markets.",
    method: "Non-Laser",
    footprint: "Regional chain",
    locationCount: 3,
    markets: ["Austin, TX", "Chicago, IL", "Draper, UT"],
    totalReviews: 73,
    avgRating: 4.0,
    tags: ["TEPR", "Non-Laser"],
    featured: true,
  },
  {
    id: "inkfree-md",
    name: "InkFree, MD",
    slug: "inkfree-md",
    descriptor: "Physician-led PicoSure clinic in Houston with high review volume.",
    method: "Laser",
    footprint: "Single location",
    locationCount: 1,
    markets: ["Houston, TX"],
    totalReviews: 36,
    avgRating: 4.4,
    tags: ["Medical", "Laser", "PicoSure", "High Rated"],
    featured: true,
  },
  {
    id: "medermis-laser-clinic",
    name: "MEDermis Laser Clinic",
    slug: "medermis-laser-clinic",
    descriptor: "Dedicated Spectra laser removal specialist in Austin. 11 years of practice.",
    method: "Laser",
    footprint: "Single location",
    locationCount: 1,
    markets: ["Austin, TX"],
    totalReviews: 42,
    avgRating: 4.3,
    tags: ["Laser", "Spectra", "Specialist", "Established"],
    featured: true,
  },
  {
    id: "dermsurgery-associates",
    name: "DermSurgery Associates",
    slug: "dermsurgery-associates",
    descriptor: "Long-established Houston dermatology practice. Q-Switch laser removal.",
    method: "Laser",
    footprint: "Single location",
    locationCount: 1,
    markets: ["Houston, TX"],
    totalReviews: 33,
    avgRating: 4.3,
    tags: ["Medical", "Laser", "Q-Switch", "Established"],
    featured: true,
  },
];
