import type { Provider } from "@/types/provider";

export const providers: Provider[] = [

  // ── inkOUT (TEPR brand) ──────────────────────────────────────────────────
  {
    id: "inkout-austin",
    name: "inkOUT",
    slug: "inkout-austin",
    brand: "inkOUT",
    market: "Austin, TX",
    rating: 4.5,
    reviewCount: 52,
    specialty: "Non-Laser Tattoo Removal",
    yearsActive: 7,
    location: "Austin, TX",
    photo: "/images/providers/inkout-austin.jpg",
    featured: true,
    featuredScore: 94,
    summary:
      "inkOUT's Austin location leads the brand in review volume. Strong patient communication and consistent session planning. High satisfaction across ink types.",
    tags: ["TEPR", "Non-Laser", "Medical Spa", "National Chain", "Top Rated"],
    website: "https://inkout.io",
    webSummary: "inkOUT performs tattoo and permanent makeup removal using its patented TEPRderm device, which applies a dot-pattern template called tegulae and delivers a proprietary TEPRsol solution through precision superficial dermabrasion. Ink is then expelled through the skin surface as crusting during natural healing rather than fragmented into the lymphatic system, with each session removing up to 35 percent of ink. The brand reports over 30,000 treatments and 10,000 tattoos removed, with most complete removals taking three to five sessions over ten to fifteen months.",
    googleBusinessUrl: "",
  },
  {
    id: "inkout-chicago",
    name: "inkOUT",
    slug: "inkout-chicago",
    brand: "inkOUT",
    market: "Chicago, IL",
    rating: 4.4,
    reviewCount: 41,
    specialty: "Non-Laser Tattoo Removal",
    yearsActive: 6,
    location: "Chicago, IL",
    photo: "/images/providers/inkout-chicago.jpg",
    featured: true,
    featuredScore: 89,
    summary:
      "Well-reviewed Chicago location with consistent fading outcomes. Reviewers note clear session expectations and responsive aftercare support.",
    tags: ["TEPR", "Non-Laser", "Medical Spa", "National Chain", "High Rated"],
    website: "https://inkout.io",
    webSummary: "inkOUT performs tattoo and permanent makeup removal using its patented TEPRderm device, which applies a dot-pattern template called tegulae and delivers a proprietary TEPRsol solution through precision superficial dermabrasion. Ink is then expelled through the skin surface as crusting during natural healing rather than fragmented into the lymphatic system, with each session removing up to 35 percent of ink. The brand reports over 30,000 treatments and 10,000 tattoos removed, with most complete removals taking three to five sessions over ten to fifteen months.",
    googleBusinessUrl: "",
  },
  {
    id: "inkout-houston",
    name: "inkOUT",
    slug: "inkout-houston",
    brand: "inkOUT",
    market: "Houston, TX",
    rating: 4.3,
    reviewCount: 38,
    specialty: "Non-Laser Tattoo Removal",
    yearsActive: 5,
    location: "Houston, TX",
    photo: "/images/providers/inkout-houston.jpg",
    featured: true,
    featuredScore: 85,
    summary:
      "Solid regional performer with above-average ratings. Patients report clear timelines and good results across standard ink types.",
    tags: ["TEPR", "Non-Laser", "Medical Spa", "National Chain", "High Rated"],
    website: "https://inkout.io",
    webSummary: "inkOUT performs tattoo and permanent makeup removal using its patented TEPRderm device, which applies a dot-pattern template called tegulae and delivers a proprietary TEPRsol solution through precision superficial dermabrasion. Ink is then expelled through the skin surface as crusting during natural healing rather than fragmented into the lymphatic system, with each session removing up to 35 percent of ink. The brand reports over 30,000 treatments and 10,000 tattoos removed, with most complete removals taking three to five sessions over ten to fifteen months.",
    googleBusinessUrl: "",
  },
  {
    id: "inkout-tampa",
    name: "inkOUT",
    slug: "inkout-tampa",
    brand: "inkOUT",
    market: "Tampa, FL",
    rating: 4.4,
    reviewCount: 34,
    specialty: "Non-Laser Tattoo Removal",
    yearsActive: 5,
    location: "Tampa, FL",
    photo: "/images/providers/inkout-tampa.jpg",
    featured: true,
    featuredScore: 83,
    summary:
      "Strong Tampa presence with consistently high ratings. Reviewers highlight knowledgeable staff and transparent pricing.",
    tags: ["TEPR", "Non-Laser", "Medical Spa", "National Chain", "High Rated"],
    website: "https://inkout.io",
    webSummary: "inkOUT performs tattoo and permanent makeup removal using its patented TEPRderm device, which applies a dot-pattern template called tegulae and delivers a proprietary TEPRsol solution through precision superficial dermabrasion. Ink is then expelled through the skin surface as crusting during natural healing rather than fragmented into the lymphatic system, with each session removing up to 35 percent of ink. The brand reports over 30,000 treatments and 10,000 tattoos removed, with most complete removals taking three to five sessions over ten to fifteen months.",
    googleBusinessUrl: "",
  },
  {
    id: "inkout-draper",
    name: "inkOUT",
    slug: "inkout-draper",
    brand: "inkOUT",
    market: "Draper, UT",
    rating: 4.2,
    reviewCount: 29,
    specialty: "Non-Laser Tattoo Removal",
    yearsActive: 4,
    location: "Draper, UT",
    photo: "/images/providers/inkout-draper.jpg",
    featured: false,
    featuredScore: 74,
    summary:
      "inkOUT's Utah location with growing review volume. Patients report good results and clear session planning consistent with other brand locations.",
    tags: ["TEPR", "Non-Laser", "Medical Spa", "National Chain"],
    website: "https://inkout.io",
    webSummary: "inkOUT performs tattoo and permanent makeup removal using its patented TEPRderm device, which applies a dot-pattern template called tegulae and delivers a proprietary TEPRsol solution through precision superficial dermabrasion. Ink is then expelled through the skin surface as crusting during natural healing rather than fragmented into the lymphatic system, with each session removing up to 35 percent of ink. The brand reports over 30,000 treatments and 10,000 tattoos removed, with most complete removals taking three to five sessions over ten to fifteen months.",
    googleBusinessUrl: "",
  },

  // ── Competitors ──────────────────────────────────────────────────────────
  {
    id: "arviv-medical-aesthetics",
    name: "Arviv Medical Aesthetics",
    slug: "arviv-medical-aesthetics",
    market: "Tampa, FL",
    rating: 4.2,
    reviewCount: 28,
    specialty: "Laser Tattoo Removal",
    yearsActive: 8,
    location: "Tampa, FL",
    photo: "/images/providers/arviv.jpg",
    featured: false,
    featuredScore: 70,
    summary:
      "Arviv Medical Aesthetics is a full-service medical spa led by Dr. Tali Arviv, MD, with three locations in Tampa, Miami, and Ocala, offering laser tattoo removal alongside a broader aesthetic menu that includes injectables, laser hair removal, vein treatment, body contouring, and hormone therapy. Tattoo removal is one of many services rather than the clinic's primary focus.",
    tags: ["Laser", "PicoWay", "Medical", "Medical Spa"],
    website: "https://arvivaesthetics.com",
    webSummary: "Arviv offers laser tattoo removal using PicoWay picosecond technology, positioned within a comprehensive medical spa environment under the direction of Dr. Tali Arviv, a board-certified internal medicine physician with over a decade of laser experience. The clinic emphasizes versatility across the Fitzpatrick spectrum and markets its ability to handle most tattoo types and colors. Tattoo removal is one service line among many offered at the Tampa Westchase location.",
  },
  {
    id: "clarity-skin",
    name: "Clarity Skin",
    slug: "clarity-skin",
    market: "Draper, UT",
    rating: 4.0,
    reviewCount: 22,
    specialty: "Laser Tattoo Removal",
    yearsActive: 6,
    location: "Draper, UT",
    photo: "/images/providers/clarity-skin.jpg",
    featured: false,
    featuredScore: 62,
    summary:
      "Clarity Skin is a medical spa in Draper, Utah, owned and led by four board-certified plastic surgeons, offering laser tattoo removal alongside a wide range of aesthetic services including injectables, laser hair removal, body contouring, and facials. The practice operates a single location serving the Salt Lake City metro area.",
    tags: ["Laser", "PicoWay", "Medical", "Medical Spa"],
    website: "https://clarityskin.com",
    webSummary: "Clarity Skin performs laser tattoo removal using the Candela PicoWay picosecond system, emphasizing customized treatment plans based on ink pigment, density, and skin tone. The practice is structured around Candela laser technology across multiple service lines and operates an on-site surgery center. Treatments are performed by licensed laser technicians under the oversight of the owning plastic surgeons.",
  },
  {
    id: "clean-slate-ink",
    name: "Clean Slate Ink",
    slug: "clean-slate-ink",
    market: "Austin, TX",
    rating: 3.7,
    reviewCount: 19,
    specialty: "Laser Tattoo Removal",
    yearsActive: 4,
    location: "Austin, TX",
    photo: "/images/providers/clean-slate-ink.jpg",
    featured: false,
    featuredScore: 52,
    summary:
      "Clean Slate Ink is a laser tattoo removal clinic with two locations in South Austin and Round Rock, Texas, serving the greater Austin area including Georgetown, Cedar Park, Pflugerville, and surrounding communities. The clinic focuses on tattoo removal, lightening for cover-ups, and selective partial removal, with pricing starting at 99 dollars per session.",
    tags: ["Laser", "Affordable"],
    website: "https://cleanslateink.com",
    webSummary: "Clean Slate Ink performs laser tattoo removal using FDA-cleared laser systems and the Zimmer Cryo skin-cooling device for comfort during treatment. The clinic quotes most tattoos at five to ten sessions spaced six to twelve weeks apart, and sessions run between one and fifteen minutes depending on tattoo size. Staff are described as certified and trained in laser operation, working under defined state regulations.",
  },
  {
    id: "dermsurgery-associates",
    name: "DermSurgery Associates",
    slug: "dermsurgery-associates",
    market: "Houston, TX",
    rating: 4.3,
    reviewCount: 33,
    specialty: "Laser Tattoo Removal",
    yearsActive: 12,
    location: "Houston, TX",
    photo: "/images/providers/dermsurgery.jpg",
    featured: false,
    featuredScore: 76,
    summary:
      "DermSurgery Associates is a large Greater Houston dermatology group with 12 locations across Bellaire, Houston, Pearland, Kingwood, The Woodlands, Katy, Willowbrook, Brenham, and El Campo, staffed by board-certified dermatologists and fellowship-trained Mohs surgeons. Laser tattoo removal is one offering within a broad medical, cosmetic, and surgical dermatology practice.",
    tags: ["Laser", "PicoSure", "Q-Switch", "Medical"],
    website: "https://www.dermsurgery.org",
    webSummary: "DermSurgery Associates offers laser tattoo removal using the Q-Switched Nd:YAG laser for dark pigments like black, blue, and gray, and the PicoSure picosecond laser for colored tattoos and more stubborn ink. Treatment is performed by or under the supervision of board-certified dermatologists and structured around six to eight week intervals between sessions. Tattoo removal sits within a broader cosmetic dermatology service line and is available at select locations in the group.",
  },
  {
    id: "enfuse-medical-spa",
    name: "Enfuse Medical Spa",
    slug: "enfuse-medical-spa",
    market: "Chicago, IL",
    rating: 3.8,
    reviewCount: 21,
    specialty: "Laser Tattoo Removal",
    yearsActive: 16,
    location: "Chicago, IL",
    photo: "/images/providers/enfuse.jpg",
    featured: false,
    featuredScore: 55,
    summary:
      "Enfuse Medical Spa is a queer and female-owned medical spa and hair restoration practice in Wicker Park, Chicago, established in 2010 under the ownership of Dr. Bernard Gran. The practice offers laser tattoo removal as part of a broader menu that includes injectables, laser hair removal, microblading, hair restoration, and gender-affirming care.",
    tags: ["Laser", "PicoWay", "Medical", "Medical Spa"],
    website: "https://www.enfusemedspas.com",
    webSummary: "Enfuse performs laser tattoo removal using the PicoWay picosecond system by Syneron Candela, noting the laser's shorter pulse durations and ability to address multi-color tattoos across skin types. The clinic emphasizes a small-business, inclusive atmosphere and books tattoo removal alongside medical aesthetic services like IPL photofacials, microneedling, and injectables. Treatment sessions are typically spaced six to eight weeks apart.",
  },
  {
    id: "erasable-med-spa",
    name: "Erasable Med Spa",
    slug: "erasable-med-spa",
    market: "Tampa, FL",
    rating: 3.9,
    reviewCount: 17,
    specialty: "Laser Tattoo Removal",
    yearsActive: 12,
    location: "Tampa, FL",
    photo: "/images/providers/erasable.jpg",
    featured: false,
    featuredScore: 53,
    summary:
      "Erasable Med Spa is a veteran-owned medical spa in Tampa, Florida, founded in 2014 by Lieutenant Colonel Loretta Nguyen Zanetti, APRN, originally as Erasable Ink with a single-service focus on laser tattoo removal. The practice has since expanded into a full-service med spa under co-ownership with Kristen Capo, APRN and physician partners Andrew Walter, MD and Nadia Pile, MD, offering injectables, body contouring, laser hair removal, and other aesthetic services alongside tattoo removal.",
    tags: ["Laser", "Medical", "Medical Spa"],
    website: "https://erasablemedspa.com",
    webSummary: "Erasable Med Spa uses the Cutera enlighten picosecond laser for tattoo removal, a system that offers both picosecond and nanosecond pulse durations at 1064 nm and 532 nm wavelengths. The practice applies the Kirby-Desai scale during consultation to forecast treatment outcomes and reports over 3,000 successful removals. Its roots in military recruiting and tattoo regulations shape its protocol work with service members and first responders, and the clinic now runs a Cutera enlighten training program for other practitioners.",
  },
  {
    id: "inkfree-md",
    name: "InkFree, MD",
    slug: "inkfree-md",
    market: "Houston, TX",
    rating: 4.4,
    reviewCount: 36,
    specialty: "Laser Tattoo Removal",
    yearsActive: 14,
    location: "Houston, TX",
    photo: "/images/providers/inkfree-md.jpg",
    featured: false,
    featuredScore: 81,
    summary:
      "Inkfree, MD is a physician and family-owned laser clinic in Northwest Houston, established in 2012 and led by medical director Dr. Adaeze Okeke. The clinic positions itself as a dedicated laser clinic rather than a medical spa, with tattoo removal, hair removal, and SculpSure body contouring as its three core service lines.",
    tags: ["Laser", "Medical", "Affordable", "High Rated"],
    website: "https://www.inkfreemd.com",
    webSummary: "Inkfree, MD operates the Lutronic PicoPlus, a picosecond Nd:YAG laser with four wavelengths (532 nm, 595 nm, 660 nm, and 1064 nm) and a 450 picosecond pulse width, alongside the Lutronic Spectra, a hybrid picosecond and nanosecond Nd:YAG system. The clinic claims to have been the first in the United States to commercially operate the PicoPlus. Its positioning emphasizes affordability, transparent pricing, and a physician-owned independent operating model that differentiates it from medical spas and franchise-style tattoo removal chains. Its client base is described as evenly split between female and male patients, including those preparing for military service.",
  },
  {
    id: "inklifters-aesthetica",
    name: "Inklifters (Aesthetica)",
    slug: "inklifters-aesthetica",
    market: "Pleasant Grove, UT",
    rating: 4.1,
    reviewCount: 16,
    specialty: "Laser Tattoo Removal",
    yearsActive: 18,
    location: "Pleasant Grove, UT",
    photo: "/images/providers/inklifters.jpg",
    featured: false,
    featuredScore: 57,
    summary:
      "Inklifters is a dedicated laser tattoo removal brand operated as part of Aesthetica Medical Spa and Laser Center in Pleasant Grove, Utah. The parent organization has provided laser treatments since 2006, and Inklifters has focused specifically on tattoo removal since 2007 under the medical direction of board-certified plastic surgeon Dr. Kimball M. Crofts.",
    tags: ["Laser", "PicoWay", "PicoSure", "Medical", "Medical Spa"],
    website: "https://inklifters.com",
    webSummary: "Inklifters performs laser tattoo removal using a three-wavelength PicoWay picosecond system from Candela, after adopting the PicoSure laser in 2014 and upgrading to PicoWay in 2016. The clinic charges 120 dollars per square inch per treatment, discounts for package purchases, and estimates most tattoos reach 75 percent clearance in three to five sessions. Treatments are delivered by state-licensed laser technicians under the oversight of the Aesthetica parent practice.",
  },
  {
    id: "kovak-cosmetic-center",
    name: "Kovak Cosmetic Center",
    slug: "kovak-cosmetic-center",
    market: "Chicago, IL",
    rating: 3.6,
    reviewCount: 14,
    specialty: "Laser Tattoo Removal",
    yearsActive: 27,
    location: "Oakbrook Terrace, IL",
    photo: "/images/providers/kovak.jpg",
    featured: false,
    featuredScore: 44,
    summary:
      "Kovak Cosmetic Center is a family-run cosmetic practice in Oakbrook Terrace, Illinois, led by Dr. Stanley Kovak with over 27 years of clinical experience according to company marketing. The center offers more than 25 laser systems and a broad menu of cosmetic and body contouring services, with laser tattoo removal as one line within a wide cosmetic dermatology and surgical practice.",
    tags: ["Laser", "PicoWay", "Medical"],
    website: "https://www.kovakcosmeticcenter.com",
    webSummary: "Kovak Cosmetic Center performs laser tattoo removal using PicoWay picosecond technology alongside nanosecond laser systems, allowing treatment across a wide range of ink colors and skin tones on the Fitzpatrick scale. Treatment plans are medically supervised, with most clients completing between six and ten sessions. Tattoo removal is positioned within a broader cosmetic and dermatology menu rather than as a standalone specialty.",
  },
  {
    id: "medermis-laser-clinic",
    name: "MEDermis Laser Clinic",
    slug: "medermis-laser-clinic",
    market: "Austin, TX",
    rating: 4.3,
    reviewCount: 42,
    specialty: "Laser Tattoo Removal",
    yearsActive: 19,
    location: "Austin, TX",
    photo: "/images/providers/medermis.jpg",
    featured: false,
    featuredScore: 79,
    summary:
      "MEDermis Laser Clinic is a dedicated laser tattoo removal specialist founded in 2006, operating two locations in Austin and San Antonio, Texas. The clinic focuses exclusively on tattoo removal and reports nearly 500,000 successful sessions across its two offices, with a 95 to 98 percent ink clearance rate and a flat-rate guarantee that continues treatments at no cost if ten sessions do not complete the removal.",
    tags: ["Laser", "Spectra", "Affordable"],
    website: "https://medermislaserclinic.com",
    webSummary: "MEDermis uses the Lutronic Spectra Pico Plus, a hybrid picosecond and nanosecond Nd:YAG laser platform with four wavelengths (1064 nm, 532 nm, 595 nm, and 660 nm) for all tattoo removal work. The clinic positions itself as a tattoo-removal-only specialist rather than a generalist med spa. Most clients complete treatment in three to seven sessions spaced six to eight weeks apart, with sessions lasting fifteen to thirty minutes. Treatment is performed by Certified Laser Specialists, and the clinic offers financing through Cherry and a prepaid package that includes unlimited additional sessions beyond ten at no extra cost, subject to color exclusions.",
  },
  {
    id: "removery-bucktown",
    name: "Removery (Bucktown)",
    slug: "removery-bucktown",
    brand: "Removery",
    market: "Chicago, IL",
    rating: 3.9,
    reviewCount: 27,
    specialty: "Laser Tattoo Removal",
    yearsActive: 7,
    location: "1864 N Damen Avenue, Chicago, IL 60647",
    photo: "/images/providers/removery-bucktown.jpg",
    featured: false,
    featuredScore: 63,
    summary:
      "National chain location in Chicago's Bucktown neighborhood. Consistent pricing and trained staff; some reviews flag slow session scheduling.",
    tags: ["Laser", "PicoWay", "National Chain"],
    website: "https://removery.com",
    webSummary: "Removery performs laser tattoo removal exclusively using PicoWay picosecond devices, with more than 1.6 million treatments completed across its studio network. The company operates a dedicated Clinical Advisory Board of physicians and requires its specialists to complete over 160 hours of training. Its commercial model centers on unlimited-session Complete Removal Packages sold at a single flat price rather than per-session billing, and the brand runs the INK-nitiative program offering free removal for formerly incarcerated individuals, domestic violence survivors, and those removing hate symbols.",
  },
  {
    id: "removery-lincoln-square",
    name: "Removery (Lincoln Square)",
    slug: "removery-lincoln-square",
    brand: "Removery",
    market: "Chicago, IL",
    rating: 3.8,
    reviewCount: 23,
    specialty: "Laser Tattoo Removal",
    yearsActive: 7,
    location: "4347 N Lincoln Avenue, Chicago, IL 60618",
    photo: "/images/providers/removery-lincoln-square.jpg",
    featured: false,
    featuredScore: 58,
    summary:
      "Second Chicago Removery location. Review patterns are similar to Bucktown. Reliable process, mixed feedback on aftercare communication.",
    tags: ["Laser", "PicoWay", "National Chain"],
    website: "https://removery.com",
    webSummary: "Removery performs laser tattoo removal exclusively using PicoWay picosecond devices, with more than 1.6 million treatments completed across its studio network. The company operates a dedicated Clinical Advisory Board of physicians and requires its specialists to complete over 160 hours of training. Its commercial model centers on unlimited-session Complete Removal Packages sold at a single flat price rather than per-session billing, and the brand runs the INK-nitiative program offering free removal for formerly incarcerated individuals, domestic violence survivors, and those removing hate symbols.",
  },
  {
    id: "removery-south-congress",
    name: "Removery (South Congress)",
    slug: "removery-south-congress",
    brand: "Removery",
    market: "Austin, TX",
    rating: 4.0,
    reviewCount: 31,
    specialty: "Laser Tattoo Removal",
    yearsActive: 7,
    location: "1400 South Congress Ave, Suite A170, Austin, TX 78704",
    photo: "/images/providers/removery-south-congress.jpg",
    featured: false,
    featuredScore: 67,
    summary:
      "Austin's Removery location on South Congress. Above-average for the brand; reviewers report better technician consistency than other chain locations.",
    tags: ["Laser", "PicoWay", "National Chain"],
    website: "https://removery.com",
    webSummary: "Removery performs laser tattoo removal exclusively using PicoWay picosecond devices, with more than 1.6 million treatments completed across its studio network. The company operates a dedicated Clinical Advisory Board of physicians and requires its specialists to complete over 160 hours of training. Its commercial model centers on unlimited-session Complete Removal Packages sold at a single flat price rather than per-session billing, and the brand runs the INK-nitiative program offering free removal for formerly incarcerated individuals, domestic violence survivors, and those removing hate symbols.",
  },

  // Removery expansion: Austin TX
  {
    id: "removery-round-rock",
    name: "Removery (Round Rock)",
    slug: "removery-round-rock",
    brand: "Removery",
    market: "Round Rock, TX",
    rating: 0,
    reviewCount: 0,
    specialty: "Laser Tattoo Removal",
    yearsActive: 7,
    location: "2541 South Interstate 35, Suite 100, Round Rock, TX 78664",
    photo: "/images/providers/removery-round-rock.jpg",
    featured: false,
    featuredScore: 0,
    summary: "Removery studio in Round Rock serving the greater Austin metro area. Part of the national PicoWay laser network.",
    tags: ["Laser", "PicoWay", "National Chain"],
    website: "https://removery.com",
    webSummary: "Removery performs laser tattoo removal exclusively using PicoWay picosecond devices, with more than 1.6 million treatments completed across its studio network. The company operates a dedicated Clinical Advisory Board of physicians and requires its specialists to complete over 160 hours of training. Its commercial model centers on unlimited-session Complete Removal Packages sold at a single flat price rather than per-session billing, and the brand runs the INK-nitiative program offering free removal for formerly incarcerated individuals, domestic violence survivors, and those removing hate symbols.",
  },

  // Removery expansion: Houston TX
  {
    id: "removery-hedwig-village",
    name: "Removery (Hedwig Village)",
    slug: "removery-hedwig-village",
    brand: "Removery",
    market: "Houston, TX",
    rating: 0,
    reviewCount: 0,
    specialty: "Laser Tattoo Removal",
    yearsActive: 7,
    location: "9930 Katy Freeway, Suite 400, Houston, TX 77055",
    photo: "/images/providers/removery-hedwig-village.jpg",
    featured: false,
    featuredScore: 0,
    summary: "Removery studio on the Katy Freeway corridor in west Houston. Part of the national PicoWay laser network.",
    tags: ["Laser", "PicoWay", "National Chain"],
    website: "https://removery.com",
    webSummary: "Removery performs laser tattoo removal exclusively using PicoWay picosecond devices, with more than 1.6 million treatments completed across its studio network. The company operates a dedicated Clinical Advisory Board of physicians and requires its specialists to complete over 160 hours of training. Its commercial model centers on unlimited-session Complete Removal Packages sold at a single flat price rather than per-session billing, and the brand runs the INK-nitiative program offering free removal for formerly incarcerated individuals, domestic violence survivors, and those removing hate symbols.",
  },
  {
    id: "removery-katy",
    name: "Removery (Katy)",
    slug: "removery-katy",
    brand: "Removery",
    market: "Katy, TX",
    rating: 0,
    reviewCount: 0,
    specialty: "Laser Tattoo Removal",
    yearsActive: 7,
    location: "19859 Katy Freeway, Suite A, Katy, TX 77094",
    photo: "/images/providers/removery-katy.jpg",
    featured: false,
    featuredScore: 0,
    summary: "Removery studio in Katy serving the western Houston suburbs. Part of the national PicoWay laser network.",
    tags: ["Laser", "PicoWay", "National Chain"],
    website: "https://removery.com",
    webSummary: "Removery performs laser tattoo removal exclusively using PicoWay picosecond devices, with more than 1.6 million treatments completed across its studio network. The company operates a dedicated Clinical Advisory Board of physicians and requires its specialists to complete over 160 hours of training. Its commercial model centers on unlimited-session Complete Removal Packages sold at a single flat price rather than per-session billing, and the brand runs the INK-nitiative program offering free removal for formerly incarcerated individuals, domestic violence survivors, and those removing hate symbols.",
  },
  {
    id: "removery-friendswood",
    name: "Removery (Friendswood)",
    slug: "removery-friendswood",
    brand: "Removery",
    market: "Friendswood, TX",
    rating: 0,
    reviewCount: 0,
    specialty: "Laser Tattoo Removal",
    yearsActive: 7,
    location: "19048 Gulf Fwy, Suite 106, Friendswood, TX 77546",
    photo: "/images/providers/removery-friendswood.jpg",
    featured: false,
    featuredScore: 0,
    summary: "Removery studio in Friendswood serving the south Houston suburbs. Part of the national PicoWay laser network.",
    tags: ["Laser", "PicoWay", "National Chain"],
    website: "https://removery.com",
    webSummary: "Removery performs laser tattoo removal exclusively using PicoWay picosecond devices, with more than 1.6 million treatments completed across its studio network. The company operates a dedicated Clinical Advisory Board of physicians and requires its specialists to complete over 160 hours of training. Its commercial model centers on unlimited-session Complete Removal Packages sold at a single flat price rather than per-session billing, and the brand runs the INK-nitiative program offering free removal for formerly incarcerated individuals, domestic violence survivors, and those removing hate symbols.",
  },
  {
    id: "removery-sugar-land",
    name: "Removery (Sugar Land)",
    slug: "removery-sugar-land",
    brand: "Removery",
    market: "Sugar Land, TX",
    rating: 0,
    reviewCount: 0,
    specialty: "Laser Tattoo Removal",
    yearsActive: 7,
    location: "15293 Southwest Fwy, Sugar Land, TX 77478",
    photo: "/images/providers/removery-sugar-land.jpg",
    featured: false,
    featuredScore: 0,
    summary: "Removery studio in Sugar Land serving the southwest Houston suburbs. Part of the national PicoWay laser network.",
    tags: ["Laser", "PicoWay", "National Chain"],
    website: "https://removery.com",
    webSummary: "Removery performs laser tattoo removal exclusively using PicoWay picosecond devices, with more than 1.6 million treatments completed across its studio network. The company operates a dedicated Clinical Advisory Board of physicians and requires its specialists to complete over 160 hours of training. Its commercial model centers on unlimited-session Complete Removal Packages sold at a single flat price rather than per-session billing, and the brand runs the INK-nitiative program offering free removal for formerly incarcerated individuals, domestic violence survivors, and those removing hate symbols.",
  },
  {
    id: "removery-the-woodlands",
    name: "Removery (The Woodlands)",
    slug: "removery-the-woodlands",
    brand: "Removery",
    market: "Shenandoah, TX",
    rating: 0,
    reviewCount: 0,
    specialty: "Laser Tattoo Removal",
    yearsActive: 7,
    location: "19075 I-45 North, Suite 121A, Shenandoah, TX 77385",
    photo: "/images/providers/removery-the-woodlands.jpg",
    featured: false,
    featuredScore: 0,
    summary: "Removery studio in The Woodlands area serving north Houston. Part of the national PicoWay laser network.",
    tags: ["Laser", "PicoWay", "National Chain"],
    website: "https://removery.com",
    webSummary: "Removery performs laser tattoo removal exclusively using PicoWay picosecond devices, with more than 1.6 million treatments completed across its studio network. The company operates a dedicated Clinical Advisory Board of physicians and requires its specialists to complete over 160 hours of training. Its commercial model centers on unlimited-session Complete Removal Packages sold at a single flat price rather than per-session billing, and the brand runs the INK-nitiative program offering free removal for formerly incarcerated individuals, domestic violence survivors, and those removing hate symbols.",
  },
  {
    id: "removery-rice-village",
    name: "Removery (Rice Village)",
    slug: "removery-rice-village",
    brand: "Removery",
    market: "Houston, TX",
    rating: 0,
    reviewCount: 0,
    specialty: "Laser Tattoo Removal",
    yearsActive: 7,
    location: "2530 Rice Blvd, Houston, TX 77005",
    photo: "/images/providers/removery-rice-village.jpg",
    featured: false,
    featuredScore: 0,
    summary: "Removery studio in Houston's Rice Village neighborhood. Part of the national PicoWay laser network.",
    tags: ["Laser", "PicoWay", "National Chain"],
    website: "https://removery.com",
    webSummary: "Removery performs laser tattoo removal exclusively using PicoWay picosecond devices, with more than 1.6 million treatments completed across its studio network. The company operates a dedicated Clinical Advisory Board of physicians and requires its specialists to complete over 160 hours of training. Its commercial model centers on unlimited-session Complete Removal Packages sold at a single flat price rather than per-session billing, and the brand runs the INK-nitiative program offering free removal for formerly incarcerated individuals, domestic violence survivors, and those removing hate symbols.",
  },

  // ── Austin TX competitors ────────────────────────────────────────────────
  {
    id: "think-again-tattoo-removal",
    name: "Think Again Tattoo Removal",
    slug: "think-again-tattoo-removal",
    market: "Austin, TX",
    rating: 4.9,
    reviewCount: 26,
    specialty: "Laser Tattoo Removal",
    yearsActive: 3,
    location: "Austin, TX",
    photo: "/images/providers/think-again-tattoo-removal.jpg",
    featured: false,
    featuredScore: 78,
    summary:
      "Think Again Tattoo Removal is an Australian-founded laser clinic with over 150,000 treatments internationally, opening its first U.S. location in South Austin. The clinic uses Quanta Discovery Pico Plus lasers and specializes exclusively in tattoo removal, including cosmetic tattoo and facial tattoo work.",
    tags: ["Laser", "Pico", "Affordable"],
    website: "https://thinkagaintattooremoval.com",
    webSummary: "Think Again Tattoo Removal operates exclusively as a tattoo removal clinic, using the Quanta Discovery Pico Plus — a picosecond laser capable of addressing stubborn colors including blue and green pigments. The brand originated in Australia and New Zealand, reporting over 150,000 successful treatments globally before launching its first U.S. location in Austin. All staff are trained exclusively in laser tattoo removal, including cosmetic and facial tattoo work, and pricing is packaged from $720 for complete removal.",
  },
  {
    id: "unbranded-atx",
    name: "Unbranded ATX",
    slug: "unbranded-atx",
    market: "Austin, TX",
    rating: 4.8,
    reviewCount: 50,
    specialty: "Laser Tattoo Removal",
    yearsActive: 5,
    location: "Austin, TX",
    photo: "/images/providers/unbranded-atx.jpg",
    featured: false,
    featuredScore: 85,
    summary:
      "Unbranded ATX is an owner-operated laser tattoo removal clinic in Central Austin, founded in 2020 by a nurse with a background in aesthetics. The clinic uses Astanza-backed laser technology and focuses on complete removal, fading for cover-ups, and selective partial removal.",
    tags: ["Laser", "Affordable"],
    website: "https://unbrandedatx.com",
    webSummary: "Unbranded ATX performs laser tattoo removal using FDA-approved laser technology backed by Astanza, with Zimmer Cryo skin cooling for comfort during treatment. The clinic was founded by Alan Pontious, a nurse who also holds Certified Laser Specialist (CLS) and Laser Safety Officer (LSO) certifications from New Look Laser College. Services include complete removal, selective removal, and lightening for tattoo modification. Free consultations are standard, and pricing is per-session by size with package discounts available.",
  },

  // ── LaserAway locations ───────────────────────────────────────────────────
  {
    id: "laseraway-austin",
    name: "LaserAway (Austin)",
    slug: "laseraway-austin",
    brand: "LaserAway",
    market: "Austin, TX",
    rating: 4.7,
    reviewCount: 50,
    specialty: "Laser Tattoo Removal",
    yearsActive: 8,
    location: "Austin, TX",
    photo: "/images/providers/laseraway-austin.jpg",
    featured: false,
    featuredScore: 82,
    summary:
      "LaserAway's Austin East Side location is part of the national chain's expanding Texas footprint. Strong review volume with high ratings across skin types and ink colors.",
    tags: ["Laser", "PicoSure", "National Chain"],
    website: "https://laseraway.com",
    webSummary: "LaserAway performs laser tattoo removal using Cynosure PicoSure picosecond technology alongside Nd:YAG systems, positioning the chain as a full-spectrum laser aesthetic provider. The brand operates across more than 150 locations nationally and emphasizes staff training, standardized protocols, and medical oversight. Tattoo removal is one of several core service lines alongside laser hair removal, skin rejuvenation, and body contouring. Financing is available through CareCredit and Alphaeon Credit.",
  },
  {
    id: "laseraway-chicago",
    name: "LaserAway (Chicago)",
    slug: "laseraway-chicago",
    brand: "LaserAway",
    market: "Chicago, IL",
    rating: 4.9,
    reviewCount: 50,
    specialty: "Laser Tattoo Removal",
    yearsActive: 8,
    location: "Chicago, IL",
    photo: "/images/providers/laseraway-chicago.jpg",
    featured: false,
    featuredScore: 90,
    summary:
      "LaserAway's Chicago Bucktown location is among the brand's highest-rated locations nationally. Reviewers consistently cite clean facilities, knowledgeable technicians, and strong fading results.",
    tags: ["Laser", "PicoSure", "National Chain", "High Rated"],
    website: "https://laseraway.com",
    webSummary: "LaserAway performs laser tattoo removal using Cynosure PicoSure picosecond technology alongside Nd:YAG systems, positioning the chain as a full-spectrum laser aesthetic provider. The brand operates across more than 150 locations nationally and emphasizes staff training, standardized protocols, and medical oversight. Tattoo removal is one of several core service lines alongside laser hair removal, skin rejuvenation, and body contouring. Financing is available through CareCredit and Alphaeon Credit.",
  },
  {
    id: "laseraway-houston",
    name: "LaserAway (Houston)",
    slug: "laseraway-houston",
    brand: "LaserAway",
    market: "Houston, TX",
    rating: 5.0,
    reviewCount: 50,
    specialty: "Laser Tattoo Removal",
    yearsActive: 8,
    location: "Houston, TX",
    photo: "/images/providers/laseraway-houston.jpg",
    featured: false,
    featuredScore: 91,
    summary:
      "LaserAway's Houston Galleria location holds a perfect average across its published reviews. One of the top-rated providers in the Houston market by raw score.",
    tags: ["Laser", "PicoSure", "National Chain", "High Rated"],
    website: "https://laseraway.com",
    webSummary: "LaserAway performs laser tattoo removal using Cynosure PicoSure picosecond technology alongside Nd:YAG systems, positioning the chain as a full-spectrum laser aesthetic provider. The brand operates across more than 150 locations nationally and emphasizes staff training, standardized protocols, and medical oversight. Tattoo removal is one of several core service lines alongside laser hair removal, skin rejuvenation, and body contouring. Financing is available through CareCredit and Alphaeon Credit.",
  },
  {
    id: "laseraway-tampa",
    name: "LaserAway (Tampa)",
    slug: "laseraway-tampa",
    brand: "LaserAway",
    market: "Tampa, FL",
    rating: 4.2,
    reviewCount: 50,
    specialty: "Laser Tattoo Removal",
    yearsActive: 8,
    location: "Tampa, FL",
    photo: "/images/providers/laseraway-tampa.jpg",
    featured: false,
    featuredScore: 64,
    summary:
      "LaserAway's Tampa location is the lowest-rated of the brand's four locations in the dataset. Review patterns suggest more variability in technician experience than at other chain locations.",
    tags: ["Laser", "PicoSure", "National Chain"],
    website: "https://laseraway.com",
    webSummary: "LaserAway performs laser tattoo removal using Cynosure PicoSure picosecond technology alongside Nd:YAG systems, positioning the chain as a full-spectrum laser aesthetic provider. The brand operates across more than 150 locations nationally and emphasizes staff training, standardized protocols, and medical oversight. Tattoo removal is one of several core service lines alongside laser hair removal, skin rejuvenation, and body contouring. Financing is available through CareCredit and Alphaeon Credit.",
  },

  // ── Houston TX competitors ────────────────────────────────────────────────
  {
    id: "dermaluxe-spa",
    name: "Dermaluxe Spa",
    slug: "dermaluxe-spa",
    market: "Houston, TX",
    rating: 4.8,
    reviewCount: 50,
    specialty: "Laser Tattoo Removal",
    yearsActive: 6,
    location: "Houston, TX",
    photo: "/images/providers/dermaluxe-spa.jpg",
    featured: false,
    featuredScore: 84,
    summary:
      "Dermaluxe Spa is a boutique med spa and permanent makeup studio in Houston offering both Pico laser and saline removal for tattoos and permanent makeup. The clinic uses the Enlighten III Pico laser and Li-FT saline solution, with a particular depth of experience in cosmetic tattoo removal.",
    tags: ["Laser", "Saline", "Medical Spa"],
    website: "https://dermaluxespa.com",
    webSummary: "Dermaluxe Spa performs tattoo removal using the Enlighten III Pico laser — a dual-pulse-duration system from Cutera operating at 1064 nm and 532 nm — and offers Li-FT hypertonic saline removal as a non-laser alternative, particularly for permanent makeup. The spa is a boutique operation in Houston's Westheimer corridor, with a primary focus on permanent makeup services and a secondary tattoo removal offering. Sessions start at $99 per treatment area.",
  },
  {
    id: "houston-tattoo-removal-clinic",
    name: "Houston Tattoo Removal Clinic",
    slug: "houston-tattoo-removal-clinic",
    market: "Houston, TX",
    rating: 4.9,
    reviewCount: 50,
    specialty: "Laser Tattoo Removal",
    yearsActive: 15,
    location: "Houston, TX",
    photo: "/images/providers/houston-tattoo-removal-clinic.jpg",
    featured: false,
    featuredScore: 88,
    summary:
      "Houston Tattoo Removal Clinic is a long-established dedicated removal practice with over 15 years of experience. The clinic offers free consultations and spot testing and its lasers cover all skin types including difficult ink colors like blue, green, and turquoise.",
    tags: ["Laser", "Affordable"],
    website: "https://www.tattooremovalofhouston.net",
    webSummary: "Houston Tattoo Removal Clinic is a specialist removal practice with over 15 years of clinical experience in the Houston market. The clinic provides free consultations and free spot testing before committing to treatment. Its laser systems are configured to address difficult pigments including blues, greens, and turquoise — colors that resist standard Q-switched protocols — and the clinic serves all skin types on the Fitzpatrick scale.",
  },
  {
    id: "rethink-laser",
    name: "Rethink Laser",
    slug: "rethink-laser",
    market: "Houston, TX",
    rating: 5.0,
    reviewCount: 50,
    specialty: "Laser Tattoo Removal",
    yearsActive: 5,
    location: "Houston, TX",
    photo: "/images/providers/rethink-laser.jpg",
    featured: false,
    featuredScore: 90,
    summary:
      "Rethink Laser is a dedicated laser tattoo removal clinic in Houston's Montrose neighborhood. The clinic uses Candela PicoWay and holds a perfect average across its published reviews, with technicians trained through New Look Laser College and Candela's official PicoWay program.",
    tags: ["Laser", "PicoWay", "Medical"],
    website: "https://rethinklasertattooremoval.com",
    webSummary: "Rethink Laser performs tattoo removal using the Candela PicoWay picosecond laser system, with all technicians certified as Laser Safety Officers and Certified Laser Specialists through New Look Laser College and Candela's official training program. The Houston clinic is located on Westheimer Road in the Montrose neighborhood and operates as a dedicated removal practice rather than a generalist med spa. Most tattoos require five to ten sessions, and complimentary consultations are standard.",
  },

  // ── Tampa FL competitors ──────────────────────────────────────────────────
  {
    id: "eraditatt",
    name: "EradiTatt",
    slug: "eraditatt",
    market: "Tampa, FL",
    rating: 4.7,
    reviewCount: 50,
    specialty: "Laser Tattoo Removal",
    yearsActive: 6,
    location: "Tampa, FL",
    photo: "/images/providers/eraditatt.jpg",
    featured: false,
    featuredScore: 81,
    summary:
      "EradiTatt is a dedicated laser tattoo removal clinic inside Infinity Medical Institute in Tampa's Westshore corridor. The clinic uses the PiQo4 laser with Zimmer Cryo 6 cooling and is led by Melissa, a board-certified practitioner with over 15 years of medical experience.",
    tags: ["Laser", "Medical"],
    website: "https://eraditatt.com",
    webSummary: "EradiTatt Tampa performs laser tattoo removal using the Cynosure PiQo4 — a multi-wavelength picosecond and nanosecond laser system operating at four wavelengths — paired with Zimmer Cryo 6 cooling for patient comfort. The clinic claims PiQo4 technology reduces required sessions by 20 to 50 percent compared to older systems. Most tattoos require five to twelve sessions, with appointments spaced six to twelve weeks. EradiTatt is led by Melissa, a Florida and Texas board-certified practitioner with over 15 years of medical experience.",
  },
  {
    id: "reversatatt",
    name: "ReversaTatt",
    slug: "reversatatt",
    market: "Tampa, FL",
    rating: 5.0,
    reviewCount: 50,
    specialty: "Laser Tattoo Removal",
    yearsActive: 8,
    location: "Tampa, FL",
    photo: "/images/providers/reversatatt.jpg",
    featured: false,
    featuredScore: 89,
    summary:
      "ReversaTatt is a dedicated tattoo removal clinic led by Dave, a Physician Assistant, with over 13,000 sessions completed and eight years of removal-specific experience. The Tampa location is inside the Nuviva wellness center and uses advanced Pico laser technology.",
    tags: ["Laser", "Pico", "Medical", "Affordable"],
    website: "https://reversatatt.com",
    webSummary: "ReversaTatt is a Physician Assistant-owned and operated tattoo removal practice founded over eight years ago, specializing exclusively in tattoo removal. The clinic reports over 13,000 sessions completed and uses advanced PICO laser technology. The Tampa location operates inside Nuviva Medical Weight Loss clinic at Henderson Boulevard. Free remote consultations via photo submission are available, and the clinic offers pricing transparency with discounts for stubborn tattoos requiring more than ten sessions.",
  },
  {
    id: "skintellect",
    name: "Skintellect Laser & Aesthetics",
    slug: "skintellect",
    market: "Tampa, FL",
    rating: 4.9,
    reviewCount: 50,
    specialty: "Laser Tattoo Removal",
    yearsActive: 6,
    location: "Tampa, FL",
    photo: "/images/providers/skintellect.jpg",
    featured: false,
    featuredScore: 87,
    summary:
      "Skintellect Laser & Aesthetics is a Tampa med spa using the Fotona Starwalker FracTat system — a distinctive approach that creates micro-channels before the main laser pass to help ink escape more efficiently. High ratings across tattoo and permanent makeup removal.",
    tags: ["Laser", "Medical Spa"],
    website: "https://skintellectonline.com",
    webSummary: "Skintellect performs tattoo and permanent makeup removal using the Fotona Starwalker FracTat system, which applies a fractional laser pre-treatment to create micro-size channels in the skin, allowing ink particles to escape via steam and gas pressure before the main ablative pass. The clinic positions this approach as requiring fewer sessions with faster results compared to standard picosecond protocols. The Sheldon Road location serves the northwest Tampa and Citrus Park area.",
  },

  // Removery expansion: Tampa FL
  {
    id: "removery-westshore",
    name: "Removery (Westshore)",
    slug: "removery-westshore",
    brand: "Removery",
    market: "Tampa, FL",
    rating: 0,
    reviewCount: 0,
    specialty: "Laser Tattoo Removal",
    yearsActive: 7,
    location: "130 S. West Shore Blvd., Suite 2B, Tampa, FL 33609",
    photo: "/images/providers/removery-westshore.jpg",
    featured: false,
    featuredScore: 0,
    summary: "Removery studio in Tampa's Westshore district. Part of the national PicoWay laser network.",
    tags: ["Laser", "PicoWay", "National Chain"],
    website: "https://removery.com",
    webSummary: "Removery performs laser tattoo removal exclusively using PicoWay picosecond devices, with more than 1.6 million treatments completed across its studio network. The company operates a dedicated Clinical Advisory Board of physicians and requires its specialists to complete over 160 hours of training. Its commercial model centers on unlimited-session Complete Removal Packages sold at a single flat price rather than per-session billing, and the brand runs the INK-nitiative program offering free removal for formerly incarcerated individuals, domestic violence survivors, and those removing hate symbols.",
  },
];
