import type { Provider } from "@/types/provider";

export const providers: Provider[] = [

  // ── inkOUT (TEPR brand) ──────────────────────────────────────────────────
  {
    id: "inkout-austin",
    name: "inkOUT",
    slug: "inkout-austin",
    brand: "inkOUT",
    market: "Austin, TX",
    rating: 4.5,
    reviewCount: 52,
    specialty: "Non-Laser Tattoo Removal",
    yearsActive: 7,
    location: "Austin, TX",
    photo: "/images/providers/inkout-austin.jpg",
    featured: true,
    featuredScore: 94,
    summary:
      "inkOUT's Austin location leads the brand in review volume. Strong patient communication and consistent session planning. High satisfaction across ink types.",
    tags: ["TEPR", "Non-Laser", "Top Rated"],
  },
  {
    id: "inkout-chicago",
    name: "inkOUT",
    slug: "inkout-chicago",
    brand: "inkOUT",
    market: "Chicago, IL",
    rating: 4.4,
    reviewCount: 41,
    specialty: "Non-Laser Tattoo Removal",
    yearsActive: 6,
    location: "Chicago, IL",
    photo: "/images/providers/inkout-chicago.jpg",
    featured: true,
    featuredScore: 89,
    summary:
      "Well-reviewed Chicago location with consistent fading outcomes. Reviewers note clear session expectations and responsive aftercare support.",
    tags: ["TEPR", "Non-Laser", "High Rated"],
  },
  {
    id: "inkout-houston",
    name: "inkOUT",
    slug: "inkout-houston",
    brand: "inkOUT",
    market: "Houston, TX",
    rating: 4.3,
    reviewCount: 38,
    specialty: "Non-Laser Tattoo Removal",
    yearsActive: 5,
    location: "Houston, TX",
    photo: "/images/providers/inkout-houston.jpg",
    featured: true,
    featuredScore: 85,
    summary:
      "Solid regional performer with above-average ratings. Patients report clear timelines and good results across standard ink types.",
    tags: ["TEPR", "Non-Laser", "High Rated"],
  },
  {
    id: "inkout-tampa",
    name: "inkOUT",
    slug: "inkout-tampa",
    brand: "inkOUT",
    market: "Tampa, FL",
    rating: 4.4,
    reviewCount: 34,
    specialty: "Non-Laser Tattoo Removal",
    yearsActive: 5,
    location: "Tampa, FL",
    photo: "/images/providers/inkout-tampa.jpg",
    featured: true,
    featuredScore: 83,
    summary:
      "Strong Tampa presence with consistently high ratings. Reviewers highlight knowledgeable staff and transparent pricing.",
    tags: ["TEPR", "Non-Laser", "High Rated"],
  },
  {
    id: "inkout-draper",
    name: "inkOUT",
    slug: "inkout-draper",
    brand: "inkOUT",
    market: "Draper, UT",
    rating: 4.2,
    reviewCount: 29,
    specialty: "Non-Laser Tattoo Removal",
    yearsActive: 4,
    location: "Draper, UT",
    photo: "/images/providers/inkout-draper.jpg",
    featured: false,
    featuredScore: 74,
    summary:
      "inkOUT's Utah location with growing review volume. Patients report good results and clear session planning consistent with other brand locations.",
    tags: ["TEPR", "Non-Laser"],
  },

  // ── Tatt2Away ────────────────────────────────────────────────────────────
  {
    id: "tatt2away-austin",
    name: "Tatt2Away",
    slug: "tatt2away-austin",
    brand: "Tatt2Away",
    market: "Austin, TX",
    rating: 4.1,
    reviewCount: 31,
    specialty: "Non-Laser Tattoo Removal",
    yearsActive: 6,
    location: "Austin, TX",
    photo: "/images/providers/tatt2away-austin.jpg",
    featured: true,
    featuredScore: 78,
    summary:
      "Established non-laser provider with solid Austin reviews. Reviewers note consistent fading and clear expectations around the TEPR process.",
    tags: ["TEPR", "Non-Laser"],
  },
  {
    id: "tatt2away-chicago",
    name: "Tatt2Away",
    slug: "tatt2away-chicago",
    brand: "Tatt2Away",
    market: "Chicago, IL",
    rating: 4.0,
    reviewCount: 24,
    specialty: "Non-Laser Tattoo Removal",
    yearsActive: 5,
    location: "Chicago, IL",
    photo: "/images/providers/tatt2away-chicago.jpg",
    featured: false,
    featuredScore: 68,
    summary:
      "Mid-tier performance in Chicago with generally positive reviews. Some variability in session spacing noted across reviewers.",
    tags: ["TEPR", "Non-Laser"],
  },
  {
    id: "tatt2away-draper",
    name: "Tatt2Away",
    slug: "tatt2away-draper",
    brand: "Tatt2Away",
    market: "Draper, UT",
    rating: 3.9,
    reviewCount: 18,
    specialty: "Non-Laser Tattoo Removal",
    yearsActive: 4,
    location: "Draper, UT",
    photo: "/images/providers/tatt2away-draper.jpg",
    featured: false,
    featuredScore: 58,
    summary:
      "Smaller Utah location with moderate review volume. Results are generally positive but fewer reviewers report complete removal.",
    tags: ["TEPR", "Non-Laser"],
  },

  // ── Competitors ──────────────────────────────────────────────────────────
  {
    id: "arviv-medical-aesthetics",
    name: "Arviv Medical Aesthetics",
    slug: "arviv-medical-aesthetics",
    market: "Tampa, FL",
    rating: 4.2,
    reviewCount: 28,
    specialty: "Laser Tattoo Removal",
    yearsActive: 8,
    location: "Tampa, FL",
    photo: "/images/providers/arviv.jpg",
    featured: false,
    featuredScore: 70,
    summary:
      "Medically supervised Tampa clinic with strong overall ratings. Reviewers highlight the clinical environment and thorough consultations.",
    tags: ["Medical Spa", "Laser", "PicoWay"],
  },
  {
    id: "clarity-skin",
    name: "Clarity Skin",
    slug: "clarity-skin",
    market: "Draper, UT",
    rating: 4.0,
    reviewCount: 22,
    specialty: "Laser Tattoo Removal",
    yearsActive: 6,
    location: "Draper, UT",
    photo: "/images/providers/clarity-skin.jpg",
    featured: false,
    featuredScore: 62,
    summary:
      "Established Utah laser clinic. Reviewers report satisfactory fading for standard black ink; mixed results on color.",
    tags: ["Laser", "Multi-Service", "PicoWay"],
  },
  {
    id: "clean-slate-ink",
    name: "Clean Slate Ink",
    slug: "clean-slate-ink",
    market: "Austin, TX",
    rating: 3.7,
    reviewCount: 19,
    specialty: "Laser Tattoo Removal",
    yearsActive: 4,
    location: "Austin, TX",
    photo: "/images/providers/clean-slate-ink.jpg",
    featured: false,
    featuredScore: 52,
    summary:
      "Budget-friendly Austin option with mixed reviews. Some patients report good early fading; others note slow progress and scheduling gaps.",
    tags: ["Laser", "Affordable", "Q-Switch"],
  },
  {
    id: "dermsurgery-associates",
    name: "DermSurgery Associates",
    slug: "dermsurgery-associates",
    market: "Houston, TX",
    rating: 4.3,
    reviewCount: 33,
    specialty: "Laser Tattoo Removal",
    yearsActive: 12,
    location: "Houston, TX",
    photo: "/images/providers/dermsurgery.jpg",
    featured: false,
    featuredScore: 76,
    summary:
      "Long-established Houston dermatology practice. High credibility and consistent outcomes; higher price point than standalone clinics.",
    tags: ["Medical", "Laser", "Established", "Q-Switch"],
  },
  {
    id: "enfuse-medical-spa",
    name: "Enfuse Medical Spa",
    slug: "enfuse-medical-spa",
    market: "Chicago, IL",
    rating: 3.8,
    reviewCount: 21,
    specialty: "Laser Tattoo Removal",
    yearsActive: 5,
    location: "Chicago, IL",
    photo: "/images/providers/enfuse.jpg",
    featured: false,
    featuredScore: 55,
    summary:
      "Chicago med spa offering tattoo removal alongside other aesthetic services. Reviews flag variable technician consistency.",
    tags: ["Medical Spa", "Laser", "Multi-Service", "PicoWay"],
  },
  {
    id: "erasable-med-spa",
    name: "Erasable Med Spa",
    slug: "erasable-med-spa",
    market: "Tampa, FL",
    rating: 3.9,
    reviewCount: 17,
    specialty: "Laser Tattoo Removal",
    yearsActive: 4,
    location: "Tampa, FL",
    photo: "/images/providers/erasable.jpg",
    featured: false,
    featuredScore: 53,
    summary:
      "Newer Tampa entrant with growing review volume. Generally positive early results; limited data on long-term or full removal outcomes.",
    tags: ["Medical Spa", "Laser", "Laser (multiple)"],
  },
  {
    id: "inkfree-md",
    name: "InkFree, MD",
    slug: "inkfree-md",
    market: "Houston, TX",
    rating: 4.4,
    reviewCount: 36,
    specialty: "Laser Tattoo Removal",
    yearsActive: 9,
    location: "Houston, TX",
    photo: "/images/providers/inkfree-md.jpg",
    featured: false,
    featuredScore: 81,
    summary:
      "Physician-led Houston clinic with strong outcomes and high review volume. Patients consistently report clear session plans and visible fading.",
    tags: ["Medical", "Laser", "High Rated", "PicoSure"],
  },
  {
    id: "inklifters-aesthetica",
    name: "Inklifters (Aesthetica)",
    slug: "inklifters-aesthetica",
    market: "Pleasant Grove, UT",
    rating: 4.1,
    reviewCount: 16,
    specialty: "Laser Tattoo Removal",
    yearsActive: 5,
    location: "Pleasant Grove, UT",
    photo: "/images/providers/inklifters.jpg",
    featured: false,
    featuredScore: 57,
    summary:
      "Utah Valley clinic with positive early reviews. Smaller review base but above-average satisfaction scores so far.",
    tags: ["Laser", "Boutique", "PicoWay"],
  },
  {
    id: "kovak-cosmetic-center",
    name: "Kovak Cosmetic Center",
    slug: "kovak-cosmetic-center",
    market: "Chicago, IL",
    rating: 3.6,
    reviewCount: 14,
    specialty: "Laser Tattoo Removal",
    yearsActive: 10,
    location: "Chicago, IL",
    photo: "/images/providers/kovak.jpg",
    featured: false,
    featuredScore: 44,
    summary:
      "Long-standing Chicago cosmetic center. Tattoo removal is one of many services offered; reviews reflect mixed focus and variable outcomes.",
    tags: ["Multi-Service", "Laser"],
  },
  {
    id: "medermis-laser-clinic",
    name: "MEDermis Laser Clinic",
    slug: "medermis-laser-clinic",
    market: "Austin, TX",
    rating: 4.3,
    reviewCount: 42,
    specialty: "Laser Tattoo Removal",
    yearsActive: 11,
    location: "Austin, TX",
    photo: "/images/providers/medermis.jpg",
    featured: false,
    featuredScore: 79,
    summary:
      "Dedicated laser removal clinic with high review volume in Austin. Strong track record on black and grey ink; some mixed results on complex color.",
    tags: ["Laser", "Specialist", "Established", "Spectra"],
  },
  {
    id: "removery-bucktown",
    name: "Removery (Bucktown)",
    slug: "removery-bucktown",
    brand: "Removery",
    market: "Chicago, IL",
    rating: 3.9,
    reviewCount: 27,
    specialty: "Laser Tattoo Removal",
    yearsActive: 6,
    location: "Bucktown, Chicago, IL",
    photo: "/images/providers/removery-bucktown.jpg",
    featured: false,
    featuredScore: 63,
    summary:
      "National chain location in Chicago's Bucktown neighborhood. Consistent pricing and trained staff; some reviews flag slow session scheduling.",
    tags: ["National Chain", "Laser", "PicoWay"],
  },
  {
    id: "removery-lincoln-square",
    name: "Removery (Lincoln Square)",
    slug: "removery-lincoln-square",
    brand: "Removery",
    market: "Chicago, IL",
    rating: 3.8,
    reviewCount: 23,
    specialty: "Laser Tattoo Removal",
    yearsActive: 5,
    location: "Lincoln Square, Chicago, IL",
    photo: "/images/providers/removery-lincoln-square.jpg",
    featured: false,
    featuredScore: 58,
    summary:
      "Second Chicago Removery location. Review patterns are similar to Bucktown. Reliable process, mixed feedback on aftercare communication.",
    tags: ["National Chain", "Laser", "PicoWay"],
  },
  {
    id: "removery-south-congress",
    name: "Removery (South Congress)",
    slug: "removery-south-congress",
    brand: "Removery",
    market: "Austin, TX",
    rating: 4.0,
    reviewCount: 31,
    specialty: "Laser Tattoo Removal",
    yearsActive: 6,
    location: "South Congress, Austin, TX",
    photo: "/images/providers/removery-south-congress.jpg",
    featured: false,
    featuredScore: 67,
    summary:
      "Austin's Removery location on South Congress. Above-average for the brand; reviewers report better technician consistency than other chain locations.",
    tags: ["National Chain", "Laser", "PicoWay"],
  },
  {
    id: "skintellect",
    name: "Skintellect",
    slug: "skintellect",
    market: "Tampa, FL",
    rating: 4.2,
    reviewCount: 26,
    specialty: "Laser Tattoo Removal",
    yearsActive: 6,
    location: "Tampa, FL",
    photo: "/images/providers/skintellect.jpg",
    featured: false,
    featuredScore: 69,
    summary:
      "Well-regarded Tampa clinic with above-average ratings. Reviewers highlight thorough consultations and visible progress across session types.",
    tags: ["Laser", "Boutique", "High Rated", "Fotona"],
  },
];
