import type { Review } from "@/types/review";

export const reviews: Review[] = [
  {
    id: "1",
    provider: "Invisible Ink",
    providerSlug: "invisible-ink",
    providerType: "single-location",
    locationName: "Austin, TX",
    city: "Austin",
    state: "TX",
    rating: 5,
    source: "Google",
    date: "2025-03-18",
    fullText:
      "Six sessions in and my forearm piece is nearly gone. The technician mapped out a realistic session plan from day one and stuck to it. No surprises on pricing or timeline.",
    excerpt:
      "Six sessions in and my forearm piece is nearly gone. The technician mapped out a realistic session plan from day one.",
    sessions: 6,
    tags: ["Complete Removal", "Forearm", "PicoWay"],
    scarringReported: false,
    resultsMentioned: true,
  },
  {
    id: "2",
    provider: "Ink Away",
    providerSlug: "ink-away",
    providerType: "single-location",
    locationName: "Houston, TX",
    city: "Houston",
    state: "TX",
    rating: 2,
    source: "Google",
    date: "2025-03-11",
    fullText:
      "Cancelled my appointment twice without notice. Results after four sessions are barely noticeable compared to what I was shown at consultation. Staff turnover seems high.",
    excerpt:
      "Cancelled my appointment twice without notice. Results after four sessions are barely noticeable.",
    sessions: 4,
    tags: ["Incomplete Results", "Scheduling Issues"],
    resultsMentioned: true,
    staffMentioned: true,
  },
  {
    id: "3",
    provider: "FADE Tattoo Removal",
    providerSlug: "fade-tattoo-removal",
    providerType: "single-location",
    locationName: "Chicago, IL",
    city: "Chicago",
    state: "IL",
    rating: 4,
    source: "Google",
    date: "2025-03-05",
    fullText:
      "Expensive but worth it. Same technician every session, which made a real difference. They were upfront about what would and wouldn't fully clear.",
    excerpt:
      "Expensive but worth it. Same technician every session, which made a real difference.",
    sessions: 5,
    tags: ["Color Ink", "Upper Arm"],
    costMentioned: true,
    staffMentioned: true,
  },
  {
    id: "4",
    provider: "Removery",
    providerSlug: "removery",
    providerType: "multi-location",
    locationId: "south-congress",
    locationName: "South Congress, Austin, TX",
    city: "Austin",
    state: "TX",
    rating: 4,
    source: "Google",
    date: "2025-02-28",
    fullText:
      "Solid experience overall. Pricing was clear upfront and the sessions were consistent. Would have rated higher but aftercare instructions were vague.",
    excerpt:
      "Solid experience overall. Pricing was clear upfront and the sessions were consistent.",
    sessions: 7,
    tags: ["Black Ink", "Full Removal", "Wrist"],
    costMentioned: true,
    resultsMentioned: true,
  },
  {
    id: "5",
    provider: "Clean Slate Laser",
    providerSlug: "clean-slate-laser",
    providerType: "single-location",
    locationName: "Tampa, FL",
    city: "Tampa",
    state: "FL",
    rating: 3,
    source: "Google",
    date: "2025-02-14",
    fullText:
      "Affordable and accessible but the results have been inconsistent. Different technician every visit. Three sessions in and fading is minimal on the darker areas.",
    excerpt:
      "Affordable and accessible but the results have been inconsistent. Different technician every visit.",
    sessions: 3,
    tags: ["Dark Ink", "Inconsistent Results"],
    staffMentioned: true,
    resultsMentioned: true,
  },
  {
    id: "6",
    provider: "Eraser Clinic",
    providerSlug: "eraser-clinic",
    providerType: "single-location",
    locationName: "Chicago, IL",
    city: "Chicago",
    state: "IL",
    rating: 4,
    source: "Google",
    date: "2025-01-30",
    fullText:
      "Transparent pricing model. Paid per session and knew exactly what I was getting. Slower fading on the red ink but overall happy with the process.",
    excerpt:
      "Transparent pricing model. Paid per session and knew exactly what I was getting.",
    sessions: 8,
    tags: ["Color Ink", "Transparent Pricing"],
    costMentioned: true,
    resultsMentioned: true,
  },
];
