import type { Review } from "@/types/review";

export const reviews: Review[] = [
  {
    id: "1",
    providerId: "5",
    providerName: "Invisible Ink",
    providerSlug: "invisible-ink",
    rating: 5,
    subRatings: { outcomes: 5, consistency: 5, pricing: 4, communication: 5 },
    body: "Six sessions in and my forearm piece is nearly gone. The technician mapped out a realistic session plan from day one and stuck to it. No surprises on pricing or timeline.",
    date: "2025-03-18",
    city: "Austin",
    sessions: 6,
    tags: ["Complete Removal", "Forearm", "PicoWay"],
    verified: true,
  },
  {
    id: "2",
    providerId: "4",
    providerName: "Ink Away",
    providerSlug: "ink-away",
    rating: 2,
    subRatings: { outcomes: 2, consistency: 1, pricing: 2, communication: 2 },
    body: "Cancelled my appointment twice without notice. Results after four sessions are barely noticeable compared to what I was shown at consultation. Staff turnover seems high.",
    date: "2025-03-11",
    city: "Houston",
    sessions: 4,
    tags: ["Incomplete Results", "Scheduling Issues"],
    verified: true,
  },
  {
    id: "3",
    providerId: "3",
    providerName: "FADE Tattoo Removal",
    providerSlug: "fade-tattoo-removal",
    rating: 4,
    subRatings: { outcomes: 4, consistency: 5, pricing: 3, communication: 4 },
    body: "Expensive but worth it. Same technician every session, which made a real difference. They were upfront about what would and wouldn't fully clear.",
    date: "2025-03-05",
    city: "Chicago",
    sessions: 5,
    tags: ["Color Ink", "Upper Arm"],
    verified: true,
  },
  {
    id: "4",
    providerId: "1",
    providerName: "Removery",
    providerSlug: "removery",
    rating: 4,
    subRatings: { outcomes: 4, consistency: 4, pricing: 4, communication: 3 },
    body: "Solid experience overall. Pricing was clear upfront and the sessions were consistent. Would have rated higher but aftercare instructions were vague.",
    date: "2025-02-28",
    city: "New York",
    sessions: 7,
    tags: ["Black Ink", "Full Removal", "Wrist"],
    verified: true,
  },
  {
    id: "5",
    providerId: "2",
    providerName: "Clean Slate Laser",
    providerSlug: "clean-slate-laser",
    rating: 3,
    subRatings: { outcomes: 3, consistency: 2, pricing: 4, communication: 3 },
    body: "Affordable and accessible but the results have been inconsistent. Different technician every visit. Three sessions in and fading is minimal on the darker areas.",
    date: "2025-02-14",
    city: "Tampa",
    sessions: 3,
    tags: ["Dark Ink", "Inconsistent Results"],
    verified: true,
  },
  {
    id: "6",
    providerId: "6",
    providerName: "Eraser Clinic",
    providerSlug: "eraser-clinic",
    rating: 4,
    subRatings: { outcomes: 4, consistency: 3, pricing: 5, communication: 4 },
    body: "Transparent pricing model — paid per session and knew exactly what I was getting. Slower fading on the red ink but overall happy with the process.",
    date: "2025-01-30",
    city: "Chicago",
    sessions: 8,
    tags: ["Color Ink", "Transparent Pricing"],
    verified: true,
  },
];
